

---

spring:
    profiles: integration_test

    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${embedded.mysql.host}:${embedded.mysql.port}/${embedded.mysql.schema}
        username: ${embedded.mysql.user}
        password: ${embedded.mysql.password}

embedded:
    mysql:
        enabled: true




